package com.blaec.points.utils;

import com.blaec.points.model.Story;

import java.util.List;

public class Data {
    public final static List<Story> portuguese  = List.of(
            Story.create("pt-en-a-reserva", "pt"),                          //  3.1 | 14/16[+10]
            Story.create("pt-en-o-que-voce-precisa", "pt"),                 //  3.2 | 14/16[+10]
            Story.create("pt-en-preciso-de-um-jogo", "pt"),                 //  3.3 | 14/16[+10]
            Story.create("pt-en-onde-esta-a-sua-namorada", "pt"),           //  3.4 | 14/16[+10]
            Story.create("pt-en-o-jogador-de-basquete", "pt"),              //  4.1 | 16/18[+10]
            Story.create("pt-en-uma-passagem-para-a-china", "pt"),          //  4.2 | 16/18[+10]
            Story.create("pt-en-obrigada", "pt"),                           //  4.3 | 16/18[+10]
            Story.create("pt-en-a-aula-de-danca", "pt"),                    //  4.4 | 16/18[+10]
            Story.create("pt-en-voce-nao-e-a-maria", "pt"),                 //  5.1 | 16/18[+10]
            Story.create("pt-en-jantar-de-familia", "pt"),                  //  5.2 | 16/18[+10]
            Story.create("pt-en-o-exercicio-do-junior", "pt"),              //  5.3 | 16/18[+10]
            Story.create("pt-en-o-jardim", "pt"),                           //  5.4 | 16/18[+10]
            Story.create("pt-en-a-pessoa-perfeita", "pt"),                  //  6.1 | 16/18[+10]
            Story.create("pt-en-voce-precisa-de-ajuda", "pt"),              //  6.1 | 16/18[+10]
            Story.create("pt-en-a-escolha-de-junior", "pt"),                //  6.1 | 16/18[+10]
            Story.create("pt-en-eu-quero-um-cachorro", "pt"),               //  6.1 | 16/18[+10]
            Story.create("pt-en-o-modelo", "pt"),                           //  7.1 | 16/18[+10]
            Story.create("pt-en-a-pintura", "pt"),                          //  7.2 | 16/18[+10]
            Story.create("pt-en-voce-pode-tirar-uma-foto", "pt"),           //  7.3 | 16/18[+10]
            Story.create("pt-en-um-esporte-novo", "pt"),                    //  7.4 | 16/18[+10]
            Story.create("pt-en-lucy-e-os-dinossauros", "pt"),              //  8.1 | 16/18[+10]
            Story.create("pt-en-onde-esta-minha-chave", "pt"),              //  8.2 | 16/18[+10]
            Story.create("pt-en-o-apartamento-sujo", "pt"),                 //  8.3 | 16/18[+10]
            Story.create("pt-en-os-macacos", "pt"),                         //  8.4 | 16/18[+10]
            Story.create("pt-en-isso-nao-e-arte", "pt"),                    //  9.1 | 16/18[+10]
            Story.create("pt-en-o-garcom-esta-certo", "pt"),                //  9.2 | 16/18[+10]
            Story.create("pt-en-eu-estou-doente", "pt"),                    //  9.3 | 16/18[+10]
            Story.create("pt-en-eu-quero-uma-pizza", "pt"),                 //  9.4 | 16/18[+10]
            Story.create("pt-en-o-diario", "pt"),                           // 10.1 | 16/18[+10]
            Story.create("pt-en-as-flores-de-oscar", "pt"),                 // 10.2 | 16/18[+10]
            Story.create("pt-en-sempre-atrasada", "pt"),                    // 10.3 | 16/18[+10]
            Story.create("pt-en-hoje-eu-nao-trabalho", "pt"),               // 10.4 | 16/18[+10]
            Story.create("pt-en-o-aniversario-de-junior", "pt"),            // 11.1 | 18/20[+10]
            Story.create("pt-en-o-qual-e-seu-nome", "pt"),                  // 11.2 | 18/20[+10]
            Story.create("pt-en-uma-conversa-interessante", "pt"),          // 11.3 | 18/20[+10]
            Story.create("pt-en-nao-e-para-criancas", "pt"),                // 11.4 | 18/20[+10]
            Story.create("pt-en-too-dangerous", "pt"),                      // 12.1 | 18/20[+10]
            Story.create("pt-en-desenhando-no-parque", "pt"),               // 12.2 | 18/20[+10]
            Story.create("pt-en-o-dever-de-casa", "pt"),                    // 12.3 | 18/20[+10]
            Story.create("pt-en-noite-de-pizza", "pt"),                     // 12.4 | 18/20[+10]
            Story.create("pt-en-um-jogo-importante", "pt"),                 // 13.1 | 18/20[+10]
            Story.create("pt-en-o-cafe-da-manha-do-junior", "pt"),          // 13.2 | 18/20[+10]
            Story.create("pt-en-a-minha-primeira-pintura", "pt"),           // 13.3 | 18/20[+10]
            Story.create("pt-en-o-tax", "pt"),                              // 13.4 | 18/20[+10]
            Story.create("pt-en-uma-emergencia", "pt"),                     // 14.1 | 18/20[+10]
            Story.create("pt-en-uma-carta-de-amor", "pt"),                  // 14.2 | 18/20[+10]
            Story.create("pt-en-as-plantas-de-vikram", "pt"),               // 14.3 | 18/20[+10]
            Story.create("pt-en-o-bolo", "pt"),                             // 14.4 | 18/20[+10]
            Story.create("pt-en-a-promocao", "pt"),                         // 15.1 | 18/20[+10]
            Story.create("pt-en-a-ex-namorada", "pt"),                      // 15.2 | 18/20[+10]
            Story.create("pt-en-a-musica", "pt"),                           // 15.3 | 18/20[+10]
            Story.create("pt-en-envia-um-e-mail", "pt"),                    // 15.4 | 18/20[+10]
            Story.create("pt-en-uma-excelente-professora", "pt"),           // 16.1 | 18/20[+10]
            Story.create("pt-en-um-problema-com-o-carro", "pt"),            // 16.2 | 18/20[+10]
            Story.create("pt-en-uma-viagem-de-pesca", "pt"),                // 16.3 | 18/20[+10]
            Story.create("pt-en-o-funeral-de-tubarao", "pt"),               // 16.4 | 18/20[+10]
            Story.create("pt-en-pizza-gratis", "pt"),                       // 17.1 | 18/20[+10]
            Story.create("pt-en-um-fim-estranho", "pt"),                    // 17.2 | 18/20[+10]
            Story.create("pt-en-a-minha-banda-favorita", "pt"),             // 17.3 | 18/20[+10]
            Story.create("pt-en-o-lugar-vazio", "pt"),                      // 17.4 | 18/20[+10]
            Story.create("pt-en-a-reciclagem-e-importante", "pt"),          // 18.1 | 18/20[+10]
            Story.create("pt-en-ela-terminou-comigo", "pt"),                // 18.2 | 18/20[+10]
            Story.create("pt-en-obrigada-mamae", "pt"),                     // 18.3 | 18/20[+10]
            Story.create("pt-en-voce-sabe-falar", "pt"),                    // 18.4 | 18/20[+10]
            Story.create("pt-en-acampando", "pt"),                          // 19.1 | 20/22[+10]
            Story.create("pt-en-final-de-semana-na-casa-de-bia", "pt"),     // 19.2 | 20/22[+10]
            Story.create("pt-en-o-filme-de-terror", "pt"),                  // 19.3 | 20/22[+10]
            Story.create("pt-en-ficando-velha", "pt"),                      // 19.4 | 20/22[+10]
            Story.create("pt-en-ano-novo-bia-nova", "pt"),                  // 20.1 | 20/22[+10]
            Story.create("pt-en-vou-para-roma", "pt"),                      // 20.2 | 20/22[+10]
            Story.create("pt-en-segundo-encontro", "pt"),                   // 20.3 | 20/22[+10]
            Story.create("pt-en-posso-tirar-uma-fotografia", "pt"),         // 20.4 | 20/22[+10]
            Story.create("pt-en-a-carta", "pt"),                            // 21.1 | 20/22[+10]
            Story.create("pt-en-corre-mais-rapido", "pt"),                  // 21.2 | 20/22[+10]
            Story.create("pt-en-o-cabelo-branco", "pt"),                    // 21.3 | 20/22[+10]
            Story.create("pt-en-o-vestido-rosa", "pt"),                     // 21.4 | 20/22[+10]
            Story.create("pt-en-o-elevador", "pt"),                         // 22.1 | 20/22[+10]
            Story.create("pt-en-a-festa-de-casamento", "pt"),               // 22.2 | 20/22[+10]
            Story.create("pt-en-a-sala-do-gerente", "pt"),                  // 22.3 | 20/22[+10]
            Story.create("pt-en-a-receita-da-minha-avo", "pt"),             // 22.4 | 20/22[+10]
            Story.create("pt-en-uma-historia-de-amor", "pt"),               // 23.1 | 20/22[+10]
            Story.create("pt-en-horoscopos-nunca-estao-certos", "pt"),      // 23.2 | 20/22[+10]
            Story.create("pt-en-roubaram-o-meu-sanduiche", "pt"),           // 23.3 | 20/22[+10]
            Story.create("pt-en-voce-esta-terminando-comigo", "pt"),        // 23.4 | 20/22[+10]
            Story.create("pt-en-tem-um-problema-com-meu-macarrao", "pt"),   // 24.1 | 20/22[+10]
            Story.create("pt-en-um-gosto-estranho", "pt"),                  // 24.2 | 20/22[+10]
            Story.create("pt-en-o-bolo-de-casamento", "pt"),                // 24.3 | 20/22[+10]
            Story.create("pt-en-e-amor", "pt"),                             // 24.4 | 20/22[+10]
            Story.create("pt-en-a-luta-de-boxe", "pt"),                     // 25.1 | 20/22[+10]
            Story.create("pt-en-o-pneu-vazio", "pt"),                       // 25.2 | 20/22[+10]
            Story.create("pt-en-a-nossa-tenda-nova", "pt"),                 // 25.3 | 20/22[+10]
            Story.create("pt-en-a-estreia", "pt")                           // 25.4 | 20/22[+10]
    );

    public final static List<Story> french = List.of(
            Story.create("fr-en-inspirez-expirez", "fr"),                   // 65.1 | 28/30[+10]
            Story.create("fr-en-au-premier-rang", "fr"),                    // 65.2 | 28/30[+10]
            Story.create("fr-en-la-soiree-d-eddy", "fr"),                   // 65.3 | 28/30[+10]
            Story.create("fr-en-l-enregistrement", "fr"),                   // 65.4 | 28/30[+10]
            Story.create("fr-en-mauvais-au-foot", "fr"),                    // 66.1 | 28/30[+10]
            Story.create("fr-en-quelle-est-votre-recette", "fr"),           // 66.2 | 28/30[+10]
            Story.create("fr-en-aux-infos", "fr"),                          // 66.3 | 28/30[+10]
            Story.create("fr-en-sauvez-les-animaux", "fr"),                 // 66.4 | 28/30[+10]
            Story.create("fr-en-la-nouvelle-entreprise-de-junior", "fr"),   // 67.1 | 28/30[+10]
            Story.create("fr-en-trop-d-affaires", "fr"),                    // 67.2 | 28/30[+10]
            Story.create("fr-en-cachette-secrete", "fr"),                   // 67.3 | 28/30[+10]
            Story.create("fr-en-les-armes-d-eddy", "fr"),                   // 67.4 | 28/30[+10]
            Story.create("fr-en-je-vais-bien", "fr"),                       // 68.1 | 28/30[+10]
            Story.create("fr-en-fete-surprise", "fr"),                      // 68.2 | 28/30[+10]
            Story.create("fr-en-le-bureau-de-la-directrice", "fr"),         // 68.3 | 28/30[+10]
            Story.create("fr-en-elle-est-en-colère-contre-moi", "fr"),      // 68.4 | 28/30[+10]
            Story.create("fr-en-les-meilleurs-biscuits", "fr"),             // 69.1 | 28/30[+10]
            Story.create("fr-en-les-applications-de-rencontres", "fr"),     // 69.2 | 28/30[+10]
            Story.create("fr-en-mon-cheval-me-deteste", "fr"),              // 69.3 | 28/30[+10]
            Story.create("fr-en-la-cassette-video", "fr"),                  // 69.4 | 28/30[+10]
            Story.create("fr-en-enlevez-cette-statue", "fr"),               // 70.1 | 28/30[+10]
            Story.create("fr-en-un-chapeau-minuscule", "fr"),               // 70.2 | 28/30[+10]
            Story.create("fr-en-la-montagne", "fr"),                        // 70.3 | 28/30[+10]
            Story.create("fr-en-quelqu-un-difficile", "fr"),                // 70.4 | 28/30[+10]
            Story.create("fr-en-parc-aux-pirates", "fr"),                   // 71.1 | 28/30[+10]
            Story.create("fr-en-je-peux-predire-l-aveni", "fr"),            // 71.2 | 28/30[+10]
            Story.create("fr-en-la-maison-de-l-oncle-edouard", "fr"),       // 71.3 | 28/30[+10]
            Story.create("fr-en-sors-d-ici", "fr"),                         // 71.4 | 28/30[+10]
            Story.create("fr-en-pénalités-de-retard", "fr"),                // 72.1 | 28/30[+10]
            Story.create("fr-en-au-lever-du-jour", "fr"),                   // 72.2 | 28/30[+10]
            Story.create("fr-en-un-weekend-de-detente", "fr"),              // 72.3 | 28/30[+10]
            Story.create("fr-en-randonee-en-foret", "fr")                   // 72.4 | 28/30[+10]
    );
}
